// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using azureproductapp.contexts;

#nullable disable

namespace azureproductapp.Migrations
{
    [DbContext(typeof(ProductContext))]
    partial class ProductContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("azureproductapp.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Piclink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Gaming Pc",
                            Piclink = "https://dvsujanstorage.blob.core.windows.net/products/gamingpc.jpeg",
                            Price = 100000.0
                        },
                        new
                        {
                            Id = 2,
                            Name = "PlayStation 5",
                            Piclink = "https://dvsujanstorage.blob.core.windows.net/products/ps5.jpeg",
                            Price = 50000.0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mechanical Keyboard",
                            Piclink = "https://dvsujanstorage.blob.core.windows.net/products/keyboard.jpg",
                            Price = 10000.0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Gaming Mouse",
                            Piclink = "https://dvsujanstorage.blob.core.windows.net/products/mouse.jpeg",
                            Price = 6000.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
